baseurl = "http://www.levelbits.com/"
languageCode = "en-us"
title = "Level Bits"
theme = "levelbits"
MetaDataFormat = "toml"

[params]
name = "Level Bits, LLC"
tagline = "Web & App Development"
description = "At Level Bits, our team of professionals build and create unique applications for the Web, iOS and Android platforms."
image = "http://www.levelbits.com/images/level-bits-og-image.png"
url = "http://www.levelbits.com"
site = "@LevelBits"
GoogleTagIdentifier = "GTM-NNDHJW"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 1
    identifier = "projects"
  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 2
    identifier = "services"
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
    identifier = "contact"

[params.footer]
enable = true
copyright = "© 2016 Level Bits LLC. All rights reserved."

  [[params.footer.social]]
  name = "Facebook"
  link = "https://www.facebook.com/levelbits"
  icon = "fa fa-facebook"

  [[params.footer.social]]
  name = "Twitter"
  link = "https://twitter.com/levelbits"
  icon = "fa fa-twitter"

  [[params.footer.social]]
  name = "Instagram"
  link = "https://www.instagram.com/levelbits"
  icon = "fa fa-instagram"

  [[params.footer.social]]
  name = "Google"
  link = "https://google.com/+levelbits-"
  icon = "fa fa-google-plus"

  [[params.footer.social]]
  name = "LinkedIn"
  link = "https://www.linkedin.com/company/level-bits"
  icon = "fa fa-linkedin"
